aluno/urls.py
from django.urls import path

from . import views

app_name='aluno'

urlpatterns = [
    path('lista', views.listar, name = "listar"), 
    path('cadastro', views.cadastrar,name="cadastrar"),
 ]

setup/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView


urlpatterns = [
    path('',TemplateView.as_view(template_name='escola.html')),
    path('admin/', admin.site.urls),
    path('tiposdeatividade/', include("tiposdeatividade.urls") ),
    path('aluno/', include("aluno.urls", namespace='aluno')),
    path('instrutor/', include("instrutor.urls") ),
    path('titulo/', include("titulo.urls") ),
    path('turma/', include("turma.urls") ),
    path('utilitarios/', include("utilitarios.urls") ),    
    
]

titulo/urls.py
from django.urls import path
from . import views 

app_name = 'titulo'

urlpatterns = [
    path('cadastro/', views.cadastro, name='cadastro'),
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('lista/', views.listar, name='listar'),
    path('excluir/<int:codigo>', views.excluir, name="excluir_titulo"),
    path('carregar_titulo/<int:codigo>', views.carregar_titulo, name="carregar_titulo"),
    path('atualizar_titulo/', views.atualizar, name='atualizar_titulo'),
]

turma/urls.py
from django.urls import path

from . import views

app_name='turma'

urlpatterns = [
    path('lista', views.listar, name = "listar"), 
    path('cadastro', views.cadastrar,name="cadastrar"),
 ]

turma/models.py
from django.db import models
from django.utils import timezone
from tiposdeatividade.models import TiposDeAtividade
from aluno.models import Aluno
from instrutor.models import Instrutor

# Create your models here.
class Turma(models.Model):
    numero = models.AutoField(primary_key=True,
                                  help_text='Matrícula do Aluno')
    horario_aula = models.TimeField(help_text='Informe a hora de início da Turma')
    
    duracao_aula = models.SmallIntegerField(help_text='Informe a duração em horas da Turma')

    data_inicial = models.DateField(null=False,
                                    default=timezone.now(), 
                                    help_text='Informe a data inicial da Turma')

    data_final = models.DateField(null=True,
                                  blank=True,
                                  default=timezone.now(), 
                                  help_text='Informe a data final da Turma')
    
    codigo_atividade = models.ForeignKey(TiposDeAtividade, 
                                         null=True, 
                                         blank=True,
                                         on_delete=models.CASCADE)
    
    matricula_monitor = models.ForeignKey(Aluno, 
                                         null=True, 
                                         blank=True,
                                         on_delete=models.SET_NULL,
                                         related_name='alunos')
    
    id_instrutor = models.ForeignKey(Instrutor, 
                                     null=True, 
                                     blank=True,
                                     on_delete=models.CASCADE,
                                     related_name='instrutores')
    
    def __str__(self):
        return f'{self.numero}'

turma/views.py
from django.shortcuts import render

# Create your views here.

def listar(request):
    return render(request, 'turma/listarTurma.html')

def cadastrar(request):
    return render (request, 'turma/cadastrarTurma.html')

turma/templates/turma/cadastrarTurma.html
{%extends "base_template.html"%}

{%block title%}

{%endblock%}


{%block menu%}
<div class="collapse navbar-collapse justify-content-end" id="mynavbar">
    <div class="navbar-nav">
        <a href="/" class="nav-link">Início</a>
        <a href="{% url 'turma:cadastro'%}" class="nav-link">Cadastrar</a>
        <a href="{% url 'turma:listar'%}" class="nav-link">Listar</a>
    </div>
</div>
{%endblock%}


{%block corpo%}
    <main class="container m-2 w-75 mx-auto my-font-family">

        <div class="row">
            <div class="col text-center m-0">
                <h2 class="mt-2 mb-5 my-h2">Cadastro de Turmas</h2>
            </div>
        </div>

        <!-- formulario HTML -->
        <form name="frmCadastrarTurma" action="#" method="post" class="my-label-color-purple">

            <div class="form-group">
                <label for="idHorarioAula" class="col-form-label">Horário da Aula</label>
                <input class="form-control" type="time" id="idHorarioAula" name="horarioAula" required>
            </div>

            <div class="form-group">
                <label for='idDuracaoAula'>Duração da Aula em horas</label>
                <input class="form-control" type='number' id='idDuracaoAula' name='duracaoAula' required>
            </div>

            <div class="form-group">
                <label for='idDataInicial'>Data de Início</label>
                <input class="form-control" type='date' id='idDataInicial' name='dataInicial' required>
            </div>

            <!-- montagem do combo com os tipos de atividade -->
            <div class="form-group">
                <label for="idTipoAtividade">Tipo de Atividade</label>
                <select class="form-control" id="idTipoAtividade" name="tipoAtividade">
                    <option value="0">Selecione...</option>
                    <option value="1">Programador Web</option>
                    <option value="2">Técnico em Informática</option>
                    <option value="3">Web Designer</option>
                    <option value="4">Educação Física</option>

                </select>
            </div>


            <!-- montagem do combo com os instrutores -->
            <div class="form-group">
                <label for="idInstrutor">Instrutor</label>
                <select class="form-control" id="idInstrutor" name="idInstrutor">
                    <option value="0">Selecione...</option>
                    <option value="2">Maria Joaquina</option>
                    <option value="3">Juliana Fergusson</option>
                </select>
            </div>

            <!-- montagem do combo com os alunos -->
            <div class="form-group">
                <label for="idAluno">Aluno Monitor</label>
                <select class="form-control" id="idAluno" name="matriculaAlunoMonitor">
                    <option value="0">Selecione...</option>
                    <option value="1">Marcos Ferreira</option>
                    <option value="2">José Mauro</option>
                    <option value="3">Hian Ferreira</option>
                    <option value="4">Pedro Miranda</option>
                    <option value="5">Stephanie Negri</option>
                    <option value="6">Carlos Alexandre</option>
                    <option value="7">Felipe Gomes</option>
                </select>
            </div>

            <div class="form-group my-4 text-center">
                <input type="reset" value="Limpar" class="btn btn-primary btn-md">
                <input type="submit" value="Cadastrar" class="btn btn-primary btn-md">
            </div>

        </form>

    </main>
{%endblock%}

turma/templates/turma/listarTurma.html
{%extends "base_template.html"%}

{%block title%}

{%endblock%}


{%block menu%}
<div class="collapse navbar-collapse justify-content-end" id="mynavbar">
    <div class="navbar-nav">
        <a href="/" class="nav-link">Início</a>
        <a href="{% url 'turma:cadastro'%}" class="nav-link">Cadastrar</a>
        <a href="{% url 'turma:listar'%}" class="nav-link">Listar</a>
    </div>
</div>
{%endblock%}


{%block corpo%}
    <main class="container m-2 mx-auto my-font-family">

        <div class="row">
            <div class="col text-center m-0">
                <h2 class="mt-2 mb-5 my-h2">Lista de Turmas</h2>
            </div>
        </div>

        <!-- tabela responsiva -->
        <div class="table-responsive">

            <!-- classes para tabela (Bootstrap) , tabela sem borda, conteudo alinhado ao centro, ... , width: auto -->
            <table class="table
                        table-borderless
                        text-center
                        my-table-hover
                        my-table-image
                        my-table-td-first-child
                        my-table-border-bottom
                        my-table-th
                        w-100">

                <!-- cabecalho -->
                <thead>
                    <!-- linhas -->
                    <tr>
                        <!-- colunas cabecalho -->
                        <th>Número</th>
                        <th>Horário da Aula</th>
                        <th>Duração da Aula</th>
                        <th>Data Inicial</th>
                        <th>Data Final</th>
                        <th>Atividade</th>
                        <th>Instrutor</th>
                        <th>Titularidade</th>
                        <th>Aluno Monitor</th>
                    </tr>
                </thead>

                <!-- linhas -->
                <tbody>
                    <tr>
                        <td> 1 </td>
                        <td> 10:00:00 </td>
                        <td> 2 </td>
                        <td> 01/03/2022 </td>
                        <td> -- </td>
                        <td> Programador Web </td>
                        <td> Jefferson Gonçalves </td>
                        <td> Professor Doutor </td>
                        <td> Marcos Ferreira </td>
                    </tr>
                    <tr>
                        <td> 2 </td>
                        <td> 13:00:00 </td>
                        <td> 4 </td>
                        <td> 01/03/2022 </td>
                        <td> -- </td>
                        <td> Programador Web </td>
                        <td> Jefferson Gonçalves </td>
                        <td> Professor Doutor </td>
                        <td> José Mauro </td>
                    </tr>
                    <tr>
                        <td> 3 </td>
                        <td> 18:00:00 </td>
                        <td> 4 </td>
                        <td> 01/03/2022 </td>
                        <td> -- </td>
                        <td> Programador Web </td>
                        <td> Jefferson Gonçalves </td>
                        <td> Professor Doutor </td>
                        <td> Hian Ferreira </td>
                    </tr>
                </tbody>
            </table>

        </div>

    </main>
{%endblock%}