aluno/urls.py
from django.urls import path

from . import views

app_name='aluno'

urlpatterns = [
    path('lista', views.listar, name = "listar"), 
    path('cadastro', views.cadastrar,name="cadastrar"),
 ]

instrutor/urls.py
# instrutor/urls.py
from django.urls import path
from . import views

app_name = 'instrutor'

urlpatterns = [
    path('', views.listar, name='listar'),
    path('cadastro', views.cadastro, name='cadastro'),
    path('cadastrar', views.cadastrar, name='cadastrar'),
    path('carregar/<int:codigo>/', views.carregar_instrutor, name='carregar_instrutor'),
    path('atualizar/<int:codigo>/', views.atualizar, name='atualizar'),
    path('excluir/<int:codigo>', views.excluir, name="excluir_instrutor"),
]

setup/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView


urlpatterns = [
    path('',TemplateView.as_view(template_name='escola.html')),
    path('admin/', admin.site.urls),
    path('tiposdeatividade/', include("tiposdeatividade.urls") ),
    path('aluno/', include("aluno.urls", namespace='aluno')),
    path('instrutor/', include("instrutor.urls") ),
    path('titulo/', include("titulo.urls") ),
    path('turma/', include("turma.urls") ),
    path('utilitarios/', include("utilitarios.urls") ),    
    
]

titulo/urls.py
from django.urls import path
from . import views 

app_name = 'titulo'

urlpatterns = [
    path('cadastro/', views.cadastro, name='cadastro'),
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('lista/', views.listar, name='listar'),
    path('excluir/<int:codigo>', views.excluir, name="excluir_titulo"),
    path('carregar_titulo/<int:codigo>', views.carregar_titulo, name="carregar_titulo"),
    path('atualizar_titulo/', views.atualizar, name='atualizar_titulo'),
]

instrutor/models.py
from django.db import models
from django.utils import timezone
from titulo.models import Titulo

# Create your models here.
class Instrutor(models.Model):
    id = models.AutoField(primary_key=True,
                                  help_text='Matrícula do Instrutor')
    
    rg = models.CharField(max_length=15,
                          help_text='Informe o RG do Instrutor')

    nome = models.CharField(max_length=70,
                            help_text='Informe o nome do Instrutor')
    
    descricao = models.TextField(max_length=1024,
                                 help_text='Informe a descrição do Instrutor')
    
    data_nascimento = models.DateField(null=True,
                                       blank=True,
                                       default=timezone.now, 
                                       help_text='Informe a data de nascimento do Instrutor')

    telefone = models.CharField(max_length=9,
                                help_text='Informe o telefone do Instrutor')
    
    ddd = models.CharField(max_length=3,
                           help_text='Informe o DDD do telefone do Instrutor')
    
    codigo_titulo = models.ForeignKey(Titulo, null = True, blank=True,
                                      related_name='titulos',
                                      on_delete=models.SET_NULL,
                                      db_column='titulo_codigo')


    def __str__(self):
        return f'{self.id} - {self.nome}'

instrutor/forms.py
from django import forms
from .models import Instrutor

class InstrutorForm(forms.ModelForm):
    class Meta:
        model = Instrutor
        fields = ['nome', 'descricao']  # Ajuste conforme os campos do modelo


class InstrutorAtualizarForm(forms.ModelForm):
    class Meta:
        model = Instrutor
        fields = ['nome', 'descricao']  # Mesmo campos ou apenas os editáveis

instrutor/views.py
from django.shortcuts import render, redirect, get_object_or_404
from instrutor.models import Instrutor
from instrutor.forms import InstrutorForm, InstrutorAtualizarForm


def listar(request):
    instrutores = Instrutor.objects.all()
    return render(request, 'instrutor/listarInstrutor.html', {'instrutores': instrutores})

# carregar a pagina para cadastrar um titulo na base de dados
def cadastro(request):
    return render(request, 'instrutor/cadastroInstrutor.html')

def cadastrar(request):
    if request.method == 'POST':
        form = InstrutorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('instrutor:listar')
    else:
        form = InstrutorForm()
    return render(request, 'instrutor/cadastroInstrutor.html', {'form': form})


def carregar_instrutor(request, codigo):
    instrutor = get_object_or_404(Instrutor, pk=codigo)
    form = InstrutorAtualizarForm(instance=instrutor)
    return render(request, 'instrutor/atualizarInstrutor.html', {'form': form, 'instrutor': instrutor})


def atualizar(request, codigo):
    instrutor = get_object_or_404(Instrutor, pk=codigo)

    if request.method == 'POST':
        form = InstrutorAtualizarForm(request.POST, instance=instrutor)
        if form.is_valid():
            form.save()
            return redirect('instrutor:listar')
        else:
            return render(request, 'instrutor/atualizarInstrutor.html', {'form': form, 'instrutor': instrutor})

    return redirect('instrutor:carregar_instrutor', codigo=codigo)

# excluir um instrutor
def excluir(request, codigo):
    instrutor = Instrutor.objects.get(pk=codigo)
    instrutor.delete()

    return redirect('instrutor:listar')

instrutor/templates/instrutor/atualizarInstrutor.html
{% extends "base_template.html" %}

{% block title %}
    <title>Django - Exercícios</title>
{% endblock %}

{% block menu %}
    <div class="collapse navbar-collapse justify-content-end" id="mynavbar">
        <div class="navbar-nav">
            <a href="/" class="nav-link">Início</a>
            <a href="{% url 'titulo:cadastro' %}" class="nav-link">Cadastrar</a>
            <a href="{% url 'titulo:listar' %}" class="nav-link">Listar</a>
        </div>
    </div>
{% endblock %}

{% block corpo %}
    <!-- main -->
    <main class="container m-2 w-75 mx-auto my-font-family">

        <div class="row">
            <div class="col text-center m-0">
                <h2 class="mt-2 mb-5 my-h2">Atualização de Instrutores</h2>
            </div>
        </div>

        <!-- formulario HTML -->
        <form name="instrutorAtualizarForm" action="{% url 'instrutor:atualizar' instrutor.pk %}" method="post" class="my-label-color-purple">
            {% csrf_token %}
            
            <div class="form-group">
                <label for="idCodigo" class="col-form-label">Código</label>
                <input class="form-control" type="text" id="idCodigo" name="codigo" value="{{ instrutor.codigo }}" readonly>  
            </div>

            <div class="form-group">
                <label for="idDescricao">Descrição</label>
                <input class="form-control" type="text" id="idDescricao" name="descricao" value="{{ instrutor.descricao }}" maxlength="70" required> 
            </div>
            
            <div class="form-group my-4 text-center">
                <input type="reset" value="Limpar" class="btn btn-primary btn-md">
                <input type="submit" value="Atualizar" class="btn btn-primary btn-md">
            </div>

        </form>

    </main>
{% endblock %}



instrutor/templates/instrutor/cadastrarInstrutor.html
{%extends "base_template.html"%}

{%block title%}


{%endblock%}


 {%block menu%}
    <div class="collapse navbar-collapse justify-content-end" id="mynavbar">
    <div class="navbar-nav">
        <a href="/" class="nav-link">Início</a>
        <a href="{% url 'instrutor:cadastro'%}" class="nav-link">Cadastrar</a>
        <a href="{% url 'instrutor:listar'%}" class="nav-link">Listar</a>
    </div>
</div>
 {%endblock%}

 {%block corpo%}
 <main class="container m-2 w-75 mx-auto my-font-family">

        <div class="row">
            <div class="col text-center m-0">
                <h2 class="mt-2 mb-5 my-h2">Cadastro de Instrutores</h2>
            </div>
        </div>

        <!-- formulario HTML -->
        <form name="frmCadastrarInstrutor" action="#" method="post" class="my-label-color-purple">

            {% csrf_token %}

            <div class="form-group">
                <label for="idNomeInstrutor" class="col-form-label">Nome do Instrutor</label>
                <input class="form-control" type="text" id="idNomeInstrutor" name="nome"
                    placeholder="Informe o nome do instrutor" maxlength="70" required>
            </div>

            <div class="form-group">
                <label for='idRg'>RG</label>
                <input class="form-control" type='text' id='idRg' name='rg' placeholder="Informe o RG" maxlength="45"
                    required>
            </div>

            <div class="form-group">
                <label for='idDataNascimento'>Data de Nascimento</label>
                <input class="form-control" type='date' id='idDataNascimento' name='dataNascimento' required>
            </div>

            <div class="form-group row">
                <div class="col-sm-6">
                    <label for='idDdd'>DDD</label>
                    <input class="form-control" type='ddd' id='idDataNascimento' name='ddd' maxlength="3" required>
                </div>
                <div class="col-sm-6">
                    <label for='idTelefone'>Telefone</label>
                    <input class="form-control" type='text' id='idTelefone' name='telefone' maxlength="9" required>
                </div>
            </div>

            <div class="form-group">
                <label for="idTitulo">Título do Professor</label>
                <select class="form-control" id="idTitulo" name="codigoTitulo">
                    <option value="0">Selecione...</option>
                    <option value="1">Professor Doutor</option>
                    <option value="2">Professor Sabe-Tudo</option>
                    <option value="3">Professor Estagiário</option>

                </select>
            </div>

            <div class="form-group my-4 text-center">
                <input type="reset" value="Limpar" class="btn btn-primary btn-md">
                <input type="submit" value="Cadastrar" class="btn btn-primary btn-md">
            </div>

        </form>

    </main>
 {%endblock%}

instrutor/templates/instrutor/cadastroInstrutor.html
{%extends "base_template.html"%}

{%block title%}


{%endblock%}


 {%block menu%}
    <div class="collapse navbar-collapse justify-content-end" id="mynavbar">
    <div class="navbar-nav">
        <a href="/" class="nav-link">Início</a>
        <a href="{% url 'instrutor:cadastro'%}" class="nav-link">Cadastrar</a>
        <a href="{% url 'instrutor:listar'%}" class="nav-link">Listar</a>
    </div>
</div>
 {%endblock%}

 {%block corpo%}
 <main class="container m-2 w-75 mx-auto my-font-family">

        <div class="row">
            <div class="col text-center m-0">
                <h2 class="mt-2 mb-5 my-h2">Cadastro de Instrutores</h2>
            </div>
        </div>

        <!-- formulario HTML -->
        <form name="frmCadastrarInstrutor" action="#" method="post" class="my-label-color-purple">

            {% csrf_token %}

            <div class="form-group">
                <label for="idNomeInstrutor" class="col-form-label">Nome do Instrutor</label>
                <input class="form-control" type="text" id="idNomeInstrutor" name="nome"
                    placeholder="Informe o nome do instrutor" maxlength="70" required>
            </div>

            <div class="form-group">
                <label for='idRg'>RG</label>
                <input class="form-control" type='text' id='idRg' name='rg' placeholder="Informe o RG" maxlength="45"
                    required>
            </div>

            <div class="form-group">
                <label for='idDataNascimento'>Data de Nascimento</label>
                <input class="form-control" type='date' id='idDataNascimento' name='dataNascimento' required>
            </div>

            <div class="form-group row">
                <div class="col-sm-6">
                    <label for='idDdd'>DDD</label>
                    <input class="form-control" type='ddd' id='idDataNascimento' name='ddd' maxlength="3" required>
                </div>
                <div class="col-sm-6">
                    <label for='idTelefone'>Telefone</label>
                    <input class="form-control" type='text' id='idTelefone' name='telefone' maxlength="9" required>
                </div>
            </div>

            <div class="form-group">
                <label for="idTitulo">Título do Professor</label>
                <select class="form-control" id="idTitulo" name="codigoTitulo">
                    <option value="0">Selecione...</option>
                    <option value="1">Professor Doutor</option>
                    <option value="2">Professor Sabe-Tudo</option>
                    <option value="3">Professor Estagiário</option>

                </select>
            </div>

            <div class="form-group my-4 text-center">
                <input type="reset" value="Limpar" class="btn btn-primary btn-md">
                <input type="submit" value="Cadastrar" class="btn btn-primary btn-md">
            </div>

        </form>

    </main>
 {%endblock%}

instrutor/templates/instrutor/listarInstrutor.html
{%extends "base_template.html"%}

{%block title%}
        <title>Django - Exercícios</title>
    {%endblock%}

    {%block menu%}
    <div class="collapse navbar-collapse justify-content-end" id="mynavbar">
        <div class="navbar-nav">
            <a href="/" class="nav-link">Início</a>
            <a href="{% url 'instrutor:cadastro' %}" class="nav-link">Cadastrar</a>
            <a href="{% url 'instrutor:listar' %}" class="nav-link">Listar </a>
        </div>
    </div>
    {%endblock%}

    {%block corpo%}
    <main class="container m-2 mx-auto my-font-family">

        <div class="row">
            <div class="col text-center m-0">
                <h2 class="mt-2 mb-5 my-h2">Lista de Instrutores</h2>
            </div>
        </div>

        <!-- tabela responsiva -->
        <div class="table-responsive">

            <!-- classes para tabela (Bootstrap) , tabela sem borda, conteudo alinhado ao centro, ... , width: auto -->
            <table class="table
                        table-borderless
                        text-center
                        my-table-hover
                        my-table-image
                        my-table-td-first-child
                        my-table-border-bottom
                        my-table-th
                        w-100">

                <!-- cabecalho -->
                <thead>
                    <!-- linhas -->
                    <tr>
                        <!-- colunas cabecalho -->
                        <th>Id</th>
                        <th>Nome</th>
                        <th>RG</th>
                        <th>Data Nascimento</th>
                        <th>DDD</th>
                        <th>Telefone</th>
                        <th>Titularidade</th>
                    </tr>
                </thead>

                <!-- linhas -->
                <tr>
                    <td> 1 </td>
                    <td> Jefferson Gonçalves </td>
                    <td> 099998888 </td>
                    <td> 05/10/1978 </td>
                    <td> 021 </td>
                    <td> 897698512 </td>
                    <td> Professor Doutor </td>
                </tr>
                <tr>
                    <td> 2 </td>
                    <td> Maria Joaquina </td>
                    <td> 125487966 </td>
                    <td> 10/01/1987 </td>
                    <td> 021 </td>
                    <td> 12322211 </td>
                    <td> Professor Doutor </td>
                </tr>
                <tr>
                    <td> 3 </td>
                    <td> Juliana Fergusson </td>
                    <td> 874895692 </td>
                    <td> 15/11/1968 </td>
                    <td> 022 </td>
                    <td> 87474774 </td>
                    <td> Professor Sabe-Tudo </td>
                </tr>
            </table>
        </div>
        <!-- linhas -->
            {% for instrutor in instrutor %}
                <tr>
                    <td class="text-center"> {{ instrutor.codigo }} </td>
                    <td class="text-left"> {{ instrutor.descricao }} </td> 
                    <td>
                        <a href="{% url 'instrutor:carregar_instrutor' instrutor.codigo %}" class="btn btn-mini"><i class="far fa-edit"></i></a>
                        <button type="button" class="btn" role="button" data-target="#modalExcluirInstrutor"
                                data-toggle="modal"  
                                {% comment %} data-descricao="{{ titulo.descricao }}" {% endcomment %}
                                data-url="{% url 'instrutor:excluir_instrutor' instrutor.codigo %}">
                            <i class="far fa-trash-alt"></i>
                        </button>
                    </td>
                </tr>
            {% endfor %}

    {%endblock%}

    {% block javascript_complementar %}
    <!-- Prepara o modal com os dados da imagem do instrutor a ser excluido -->
    <script type="text/javascript">
        $(document).ready(function() {
            $('#modalExcluirInstrutor').on('show.bs.modal', function(event) {
                var descricao = $(event.relatedTarget).data('descricao');
                var urlExcluir = $(event.relatedTarget).data('url');
                $("#mensagemExclusao").text("Instrutor [ " + descricao + "  ]?");

                $.fn.excluirInstrutor = function() {
                    var url = $(event.relatedTarget).data('url');
                    location.replace(url);
                }
            });
        
            $("#btnExcluir").on('click', function() {
                $.fn.excluirInstrutor();
                return false;
            });            
        });
    </script>
{% endblock %}